kind: Deployment
apiVersion: apps/v1
metadata:
  name: calculadora
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculadora
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calculadora
    spec:
      containers:
        - name: calculadora
          image: 'acrgmblab.azurecr.io/calculadora:v1'
          ports:
            - name: console
              containerPort: 7600
              protocol: TCP
            - name: traffic
              containerPort: 7800
              protocol: TCP
          env:
            - name: LICENSE
              value: accept
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: acr-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
