apiVersion: v1
baseDomain: lab.azure
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 1024 
      type: Standard_D8s_v3
      zones:
      - "1"
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D16s_v3
      osDisk:
        diskSizeGB: 512
      zones:
      - "1"
  replicas: 1
metadata:
  name: cp4i-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.2.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: eastus2
    baseDomainResourceGroupName: LAB_OP
    networkResourceGroupName: LAB_OP
    virtualNetwork: lab_vnet 
    controlPlaneSubnet: Control
    computeSubnet: compute
pullSecret: '{"auths":{"BastionOp.lab.azure:5000":{"auth":"YWRtaW46cGFzc3cwcmQ="},"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZDJlMTNiZTQ5YjNmNDFlODg3MmI1OTliN
GE5MDIxODg6WVBHN0NYTllNVVgzWDlZNllOOUtVTFlJMjZQVVpBVFpFNkwzQkpYRDNQSDVENkhZUDJERkZITTRSOTlVUVUwWg=="},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZDJlMTNiZTQ5YjNmNDFlODg3M
mI1OTliNGE5MDIxODg6WVBHN0NYTllNVVgzWDlZNllOOUtVTFlJMjZQVVpBVFpFNkwzQkpYRDNQSDVENkhZUDJERkZITTRSOTlVUVUwWg=="},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWY1NDg5YmY4LTg0OGUtNDAzYy1hY
mU1LWFiNjMzNjNmNDBhYjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1PRFUwWVRVME56UXpZbVkwWkdZNFltVTFNVEpqWkdWaFlqUmxZakZqT1NKOS5LU1NOMjljOUI3YzBlbEJ6UUg2NlRYS2lOTTNvUzdxcU5sMGFRUGVrZzdtV1V3TTh
zS0I1ZTFtRmNxZTlUMzJXcFJ5RXZDZVBtOFFJeDhHYmIxUVVLZGlmekhlSnZYckh4czNmb2VyYUJlSTRSZVBzZ3lNZHFFWklqN09WUVRiOVVnb0U2OENKMlcyV1BZa0NNZFlCVDhvRjdibnUzYlBmTzBJRkZlOVpXRHlZVjNJY1hNTHlVX1NDYW1Md3RCM
HNlWmxvUDJnTG84WlNoTHE3dU94VmZXRVlCZUtrQkg5ZXFtc0tWNFM2TW95ekdEcXhtM09fN1ZGYUZIT1JyZGRYYmUyamU0MWZmWUNvXzNtcDNnRmswb0FMcUp1dVZ2R1U4ckNOTmo2bjRQaVN1ck9IcFlrcWRfaU5sUDYzQXduRjFqelBacEJjU2lKa0d
vNThIZlJ6RHJJUFM4b2g2LWdublFWUm0zejBLRG9fU3A5aHBjMElFZVozU0VsNzlSbHpwQ29GSlBjV21xUFgyQ0dTMTRZVEw3RjhOQVVQYm53akFudmYtM1BBUHhIUVQ2YWZhaGI2OWZfWFZsd0V0Vi1oS2xBVm1od1d4aUhwWGRKUDFNMExBQktvOHR5a
UFoajBhbWFHdndNWmkwX0d4TlFtOGpNdHB2T3VRQmNNS0FTMTJWWjg2Ul92SWhhVmVxenhwVzhFNWl2VFVPSldMcV8ta3I3MUhFTW9WSzVnUkkzUkZ4M1N1ZHE2bjNDQXZwbUVFdmpDMDZXZUFWZ3EzREhhb3RITVh5UzF5dDV1QkhENGxEWnRPRkxzVmM
1Um9QMWU4NnBFaXNGSFZsYVZwdERET29qdEdIUVdTdGtadWxUakI3V2VQdlltZE15dnlWRzdCR01PbDRFb2xjVQ=="},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWY1NDg5YmY4LTg0OGUtNDAzYy1hYmU1LWFiNjMzNjNmNDBhYjpleUpo
YkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSm1PRFUwWVRVME56UXpZbVkwWkdZNFltVTFNVEpqWkdWaFlqUmxZakZqT1NKOS5LU1NOMjljOUI3YzBlbEJ6UUg2NlRYS2lOTTNvUzdxcU5sMGFRUGVrZzdtV1V3TThzS0I1ZTFtRmNxZTlUMzJXcFJ5RX
ZDZVBtOFFJeDhHYmIxUVVLZGlmekhlSnZYckh4czNmb2VyYUJlSTRSZVBzZ3lNZHFFWklqN09WUVRiOVVnb0U2OENKMlcyV1BZa0NNZFlCVDhvRjdibnUzYlBmTzBJRkZlOVpXRHlZVjNJY1hNTHlVX1NDYW1Md3RCMHNlWmxvUDJnTG84WlNoTHE3dU94
VmZXRVlCZUtrQkg5ZXFtc0tWNFM2TW95ekdEcXhtM09fN1ZGYUZIT1JyZGRYYmUyamU0MWZmWUNvXzNtcDNnRmswb0FMcUp1dVZ2R1U4ckNOTmo2bjRQaVN1ck9IcFlrcWRfaU5sUDYzQXduRjFqelBacEJjU2lKa0dvNThIZlJ6RHJJUFM4b2g2LWdubl
FWUm0zejBLRG9fU3A5aHBjMElFZVozU0VsNzlSbHpwQ29GSlBjV21xUFgyQ0dTMTRZVEw3RjhOQVVQYm53akFudmYtM1BBUHhIUVQ2YWZhaGI2OWZfWFZsd0V0Vi1oS2xBVm1od1d4aUhwWGRKUDFNMExBQktvOHR5aUFoajBhbWFHdndNWmkwX0d4TlFt
OGpNdHB2T3VRQmNNS0FTMTJWWjg2Ul92SWhhVmVxenhwVzhFNWl2VFVPSldMcV8ta3I3MUhFTW9WSzVnUkkzUkZ4M1N1ZHE2bjNDQXZwbUVFdmpDMDZXZUFWZ3EzREhhb3RITVh5UzF5dDV1QkhENGxEWnRPRkxzVmM1Um9QMWU4NnBFaXNGSFZsYVZwdE
RET29qdEdIUVdTdGtadWxUakI3V2VQdlltZE15dnlWRzdCR01PbDRFb2xjVQ=="}}}' 
fips: false 
sshKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFIcTAOU5iZt62KaR9v1ZcVo6XtwyBJ7TEyNwTfVx3JB azureuser@BastionOp
publish: Internal 
imageContentSources:
- mirrors:
  - BastionOp.lab.azure:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - BastionOp.lab.azure:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    MIIGfTCCBGWgAwIBAgIUcCmNynIMjmzcP+buaMMNVtCs2sQwDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCQ1IxETAPBgNVBAgMCFNhbiBKb3NlMREwDwYDVQQHDAhT
    YW4gSm9zZTEMMAoGA1UECgwDR0JNMREwDwYDVQQLDAhTb2Z0d2FyZTERMA8GA1UE
    AwwIcmVnaXN0cnkwHhcNMjIwNDIwMjIzMTAzWhcNMzIwNDE3MjIzMTAzWjBnMQsw
    CQYDVQQGEwJDUjERMA8GA1UECAwIU2FuIEpvc2UxETAPBgNVBAcMCFNhbiBKb3Nl
    MQwwCgYDVQQKDANHQk0xETAPBgNVBAsMCFNvZnR3YXJlMREwDwYDVQQDDAhyZWdp
    c3RyeTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALK9PK98HmWVTD/O
    dmdlAfhkgdCRfxI+p3ivULKLsay5KhBON7hi4QBP7zQsUb71lg11bbB4VAfMF8wQ
    Rw8chlrwTwFifmZLJU2JLve54I/S27XvxwQjUJOIWNxcfAtn3XqSmtWHhjuGH/K9
    wQ8BtW6C83q8kg86+9MBm4/vd5GbfLf/A7vWToiSyFEwtkC/TXik0lCJgRRLjIXS
    //HKm7jTypqUMAqWntfYCDbLx77E2Ui73qFn9iWif8BbkRbdaNqJ/T1/MhilenPO
    TIgEs5sObSBaelriGV6hcQnKu34IxjlwcybTD6V3rqA6xOGuMycBHzGKMB+cwhwN
    QH4nGX806vwUH7A5bba/pUF+Vh59beCvJ2vE9DSnbrNOAGbzEdGtW3Q5zI1+OvN/
    4Bf9HHEpR7nn+25J7N4TH4LGdR6+z50MWY0KdIUs35a4OfldGlUU3N1cPFBsd1bg
    Ir41ljROl5wLwkBDv98QYiDXGN34WFyklWCAqlaTb6NwR5CPEsDc77rhl5eHmFzi
    x7Zjqw5+lKEeM9FE/Z1sayD+K9ieqyvHaBINOzwlaxgao6UFsE1mqCKOkF3dQ3PZ
    Y/ItKU41c/OaNHmfVsNCy+dA0Duy8OdYerx17/M7Y5xMQdc4hwUpVAIx/miFGPCC
    6dKi+Y8tO96lYr+4bNAUBv4/xJ7lAgMBAAGjggEfMIIBGzALBgNVHQ8EBAMCBDAw
    EwYDVR0lBAwwCgYIKwYBBQUHAwEwWAYDVR0RBFEwT4IJbG9jYWxob3N0gghyZWdp
    c3RyeYIJQmFzdGlvbk9wghJyZWdpc3RyeS5sYWIuYXp1cmWCE0Jhc3Rpb25PcC5s
    YWIuYXp1cmWHBH8AAAEwDAYDVR0TBAUwAwEB/zCBjgYDVR0jBIGGMIGDoWukaTBn
    MQswCQYDVQQGEwJDUjERMA8GA1UECAwIU2FuIEpvc2UxETAPBgNVBAcMCFNhbiBK
    b3NlMQwwCgYDVQQKDANHQk0xETAPBgNVBAsMCFNvZnR3YXJlMREwDwYDVQQDDAhy
    ZWdpc3RyeYIUcCmNynIMjmzcP+buaMMNVtCs2sQwDQYJKoZIhvcNAQELBQADggIB
    ADe6xLC3TQPJuw5RBtA0xMEOjNWqQpAq2aEXc8/NYGS8gqfPWFOe8VBOink/4R1H
    wcZ80Y57bGSeu7hRALdC13FfBZTavhEe/G/W2cNBzBN4aW+OJn0p4k6n8gq9I1b6
    MFfYxBo8sVU7dXJz6PO0AjrLwG+G+d6sSOTshUMmEkHYCfQvBexJctPovsKQuuq4
    P+XIR3z8rUMxt9T4tJjoqHiyK1FzxqCUnaNF1cDb3am9sfydU3lhZ6Doatfd52ZZ
    m+pDKi6rrm1sydDXJ4//kxL4D8KCChWSMtk1+rfG/FnNcDCXfrqQ4+WmXduwSlZX
    AFryIo+ZaEZD6cPZSmsxl4aNW+XBNNC5Hr7pUXGEeB3p4Q+3dfIk4HCSXlNw7zld
    /kcyF5a+O3I0TAjkqGudZl3G9Jq0JAzSF32JLG7h1HzKZ+6UEyFFWTfLBCSzOvHg
    oOTpjIafV83WBmYxfKJQ9uvFHR7eneFpoLg26BWW2BZeo9I+eH8nJ84Y0tbVYMfP
    Z9voq30G7W8MAjmIMCGOci9AuWxl64UlSD9C4JVXoUeSQR80GSpkWPwPumRGoao2
    M9S3oTp/Iazc7Zb1v9icHCbdnAcvYFIVr1XGRW23qmaKICHBjqJL7ve8Y/1nqrt9
    ZFHOJ2xvoiU4r1EE3btHkbOsOEzwZA72Ma1I+X26MnZu
    -----END CERTIFICATE-----
